  name: HeadDrop
  main: hdhotdog.advi.plugins.Main
  version: 1.0.0
  api-version: "1.13"
  description: Player Head Drop Plugin
  commands:
    tabu:
      description: the tabu game
      usage: /tabu <param>
    vanish:
      description: makes the player invisible to others
      usage: /vanish
    countdown:
      description: a countdown
      usage: /cd <seconds> <"message"> <command>
      aliases:
        - cd