  name: HeadDrop
  main: hdhotdog.advi.plugins.Main
  version: 1.0.0
  api-version: "1.13"
  description: Player Head Drop Plugin
  commands:
    tabu:
      description: the tabu game
      usage: /tabu <param>